version: '3.8'

services:
  bank-accounts:
    image: bank-accounts
    build:
      context: .
      dockerfile: bank-accounts/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped 

